const WELCOME_PAGE = "WELCOME_PAGE",
  YOUR_DATA_PAGE = "YOUR_DATA_PAGE",
  HOME_PAGE = "HOME_PAGE",
  DIARY_PAGE = "DIARY_PAGE",
  RECORD_PAGE = "RECORD_PAGE",
  CONFIG_PAGE = "CONFIG_PAGE";

export {
  WELCOME_PAGE,
  YOUR_DATA_PAGE,
  HOME_PAGE,
  DIARY_PAGE,
  RECORD_PAGE,
  CONFIG_PAGE,
};
